import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const repoRoot = join(import.meta.dir, "..");
const packageDir = join(repoRoot, "packages/point-logic");
const srcDir = join(packageDir, "src");
const distFile = join(packageDir, "dist/store-readiness.js");
const pointCli = join(repoRoot, "packages/point/src/cli.ts");

function listSourceFiles(dir: string): string[] {
	const entries: string[] = [];
	for (const name of readdirSync(dir, { withFileTypes: true })) {
		const path = join(dir, name.name);
		if (name.isDirectory()) entries.push(...listSourceFiles(path));
		else entries.push(path);
	}
	return entries;
}

describe("point-logic npm package", () => {
	test("src contains only .point sources (no hand-written TypeScript)", () => {
		const files = listSourceFiles(srcDir);
		expect(files.length).toBeGreaterThan(0);
		for (const file of files) {
			expect(file.endsWith(".point")).toBe(true);
			expect(file.endsWith(".ts")).toBe(false);
			expect(file.endsWith(".tsx")).toBe(false);
		}
	});

	test("build emits dist from .point only", async () => {
		rmSync(join(packageDir, "dist"), { recursive: true, force: true });
		await Bun.$`bun ${pointCli} check ${join(packageDir, "src/store-readiness.point")}`.cwd(packageDir).quiet();
		await Bun.$`bun ${pointCli} build src/store-readiness.point dist/store-readiness.js`.cwd(packageDir).quiet();
		expect(readFileSync(distFile, "utf8")).toContain("export function listingScore");
		expect(readFileSync(distFile, "utf8")).toContain("export function listingStatusLabel");
		expect(readFileSync(distFile, "utf8")).toContain("Generated by Point");
	});

	test("emitted exports run listing score logic", async () => {
		await Bun.$`bun run build`.cwd(packageDir).quiet();
		const { listingScore, listingStatusLabel } = await import(distFile);
		const perfect = {
			hasScreenshots: true,
			hasDescription: true,
			hasPrivacyPolicy: true,
			hasSupportUrl: true,
			hasAgeRating: true,
		};
		expect(listingScore(perfect)).toBe(100);
		expect(listingStatusLabel(100)).toBe("Ready to submit");
		expect(listingStatusLabel(60)).toBe("Almost ready");
		expect(listingStatusLabel(0)).toBe("Needs work");
	});

	test("npm pack includes dist and excludes src TypeScript", async () => {
		await Bun.$`bun run build`.cwd(packageDir).quiet();
		const packDir = join(tmpdir(), `point-logic-pack-${Date.now()}`);
		const pack = await Bun.$`npm pack --json`.cwd(packageDir).quiet();
		const parsed = JSON.parse(pack.stdout.toString()) as Array<{ filename: string }>;
		expect(parsed.length).toBe(1);
		const tarball = join(packageDir, parsed[0].filename);
		await Bun.$`mkdir -p ${packDir}`.quiet();
		await Bun.$`tar -xf ${tarball} -C ${packDir}`.quiet();
		const packedRoot = join(packDir, "package");
		expect(readFileSync(join(packedRoot, "dist/store-readiness.js"), "utf8")).toContain("listingScore");
		const packedNames = listSourceFiles(packedRoot).map((p) => p.replaceAll("\\", "/"));
		expect(packedNames.some((p) => p.endsWith("/dist/store-readiness.js"))).toBe(true);
		expect(packedNames.some((p) => p.includes("/src/"))).toBe(false);
		expect(packedNames.some((p) => p.endsWith(".ts") && p.includes("/src/"))).toBe(false);
		rmSync(tarball, { force: true });
		rmSync(packDir, { recursive: true, force: true });
	});
});
