import { describe, expect, test } from "bun:test";
import { join } from "node:path";
import {
	emitPointCoreJavaScript,
	formatProductionJavaScript,
	PRODUCTION_EMIT_HEADER,
} from "../packages/point/src/core/emit-javascript.ts";
import { parseBuildCliFlags } from "../packages/point/src/core/cli.ts";
import { parsePointSource } from "../packages/point/src/core/parser.ts";

const repoRoot = join(import.meta.dir, "..");
const pointCli = join(repoRoot, "packages/point/src/cli.ts");
const helloSource = await Bun.file(join(repoRoot, "examples/hello.point")).text();

describe("point build --production", () => {
	test("parseBuildCliFlags accepts --production before or after paths", () => {
		expect(parseBuildCliFlags(["--production", "a.point", "out.js"])).toEqual({
			production: true,
			positional: ["a.point", "out.js"],
		});
		expect(parseBuildCliFlags(["a.point", "out.js", "--production"])).toEqual({
			production: true,
			positional: ["a.point", "out.js"],
		});
		expect(parseBuildCliFlags(["a.point", "out.js"]).production).toBe(false);
	});

	test("production emit differs from dev emit and adds deploy header", () => {
		const program = parsePointSource(helloSource);
		const dev = emitPointCoreJavaScript(program);
		const prod = emitPointCoreJavaScript(program, { production: true });
		expect(prod).not.toBe(dev);
		expect(prod).toContain(PRODUCTION_EMIT_HEADER);
		expect(dev).not.toContain("production build");
		expect(prod).toContain("export async function mainMessage()");
	});

	test("formatProductionJavaScript collapses consecutive blank lines", () => {
		const formatted = formatProductionJavaScript("// Generated by Point.\n\n\n\nexport const x = 1;\n");
		expect(formatted).toContain(PRODUCTION_EMIT_HEADER);
		expect(formatted).not.toMatch(/\n\n\n/);
	});

	test("CLI build --production writes production-marked JavaScript", async () => {
		const output = join(repoRoot, "generated/hello-production-build.js");
		await Bun.$`bun ${pointCli} build --production examples/hello.point ${output}`.quiet();
		const generated = await Bun.file(output).text();
		expect(generated).toContain("production build");
		const devOutput = join(repoRoot, "generated/hello-dev-build-compare.js");
		await Bun.$`bun ${pointCli} build examples/hello.point ${devOutput}`.quiet();
		const devGenerated = await Bun.file(devOutput).text();
		expect(generated).not.toBe(devGenerated);
	});
});
