import { join } from "node:path";
import { LOCAL_POINT_CLI_REL } from "./resolve-cli.ts";

export const POINT_EDITOR_SCHEMA = "point.editor.v1";
export const VSCODE_EXTENSION_ID = "hatchingpoint.point";

export const POINT_LSP_LAUNCHER = `.point/lsp.mjs`;

export function vscodeExtensionsJson(): string {
	return `${JSON.stringify({ recommendations: [VSCODE_EXTENSION_ID] }, null, 2)}\n`;
}

export function vscodeSettingsJson(): string {
	return `${JSON.stringify(
		{
			"point.runtime": "bun",
			"point.cliPath": LOCAL_POINT_CLI_REL,
		},
		null,
		2,
	)}\n`;
}

export function pointEditorJson(projectRoot: string): string {
	return `${JSON.stringify(
		{
			schemaVersion: POINT_EDITOR_SCHEMA,
			lsp: {
				command: "bun",
				args: [POINT_LSP_LAUNCHER, "lsp"],
				description: "Project-local LSP launcher — uses node_modules/@hatchingpoint/point after bun install",
			},
			vscode: {
				extensionId: VSCODE_EXTENSION_ID,
				settingsFile: ".vscode/settings.json",
			},
			neovim: {
				configFile: ".point/editors/neovim.lua",
				notes: "Load .point/editors/neovim.lua from init.lua for project-local LSP",
			},
			zed: {
				configFile: ".point/editors/zed.json",
				notes: "Merge .point/editors/zed.json into Zed settings for this workspace",
			},
			terminal: {
				check: "bun run check",
				format: "point fmt <file.point>",
				notes: "Works in any terminal after bun install — no editor required",
			},
			projectRoot: projectRoot.replaceAll("\\", "/"),
		},
		null,
		2,
	)}\n`;
}

export function pointLspLauncherScript(): string {
	return `#!/usr/bin/env bun
/**
 * Project-local Point language server launcher.
 * Any LSP-capable editor can run: bun .point/lsp.mjs lsp
 */
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const localCli = join(projectRoot, "${LOCAL_POINT_CLI_REL}");
const subcommand = process.argv[2] ?? "lsp";
const extraArgs = process.argv.slice(3);

if (existsSync(localCli)) {
	const child = spawn("bun", [localCli, subcommand, ...extraArgs], { stdio: "inherit" });
	child.on("exit", (code, signal) => {
		if (signal) process.kill(process.pid, signal);
		process.exit(code ?? 1);
	});
} else {
	const child = spawn("point", [subcommand, ...extraArgs], { stdio: "inherit" });
	child.on("exit", (code, signal) => {
		if (signal) process.kill(process.pid, signal);
		process.exit(code ?? 1);
	});
}
`;
}

export function projectNeovimConfig(): string {
	return `-- Point LSP for this project (generated by point init)
-- In init.lua: dofile(vim.fn.getcwd() .. "/.point/editors/neovim.lua")

vim.filetype.add({
	extension = {
		point = "point",
	},
})

if not vim.lsp.config then
	vim.notify("Point: Neovim 0.11+ with vim.lsp.config is required", vim.log.levels.WARN)
	return
end

local root = vim.fn.getcwd()
local launcher = root .. "/.point/lsp.mjs"

vim.lsp.config("point", {
	cmd = { "bun", launcher, "lsp" },
	filetypes = { "point" },
	root_markers = { "point.json", "package.json", ".git" },
	settings = {},
})

vim.lsp.enable("point")
`;
}

export function projectZedConfig(): string {
	return `${JSON.stringify(
		{
			lsp: {
				point: {
					command: {
						path: "bun",
						args: [".point/lsp.mjs", "lsp"],
					},
					languages: ["Point"],
					format_on_save: "on",
				},
			},
			languages: {
				Point: {
					name: "Point",
					matcher: {
						path_suffixes: ["point"],
					},
				},
			},
		},
		null,
		2,
	)}\n`;
}

export interface EditorConfigFile {
	relativePath: string;
	content: string;
}

export function editorConfigFiles(projectRoot: string): EditorConfigFile[] {
	return [
		{ relativePath: ".vscode/extensions.json", content: vscodeExtensionsJson() },
		{ relativePath: ".vscode/settings.json", content: vscodeSettingsJson() },
		{ relativePath: ".point/editor.json", content: pointEditorJson(projectRoot) },
		{ relativePath: POINT_LSP_LAUNCHER, content: pointLspLauncherScript() },
		{ relativePath: ".point/editors/neovim.lua", content: projectNeovimConfig() },
		{ relativePath: ".point/editors/zed.json", content: projectZedConfig() },
	];
}

export function editorConfigPaths(): string[] {
	return editorConfigFiles(".").map((file) => file.relativePath);
}

export function joinProjectPath(projectRoot: string, relativePath: string): string {
	return join(projectRoot, relativePath);
}
