import type {
	PointSemanticProgram,
	PointSemanticRecordDeclaration,
	PointSemanticTypeExpression,
} from "../semantic/ast.ts";
import { toPascalCase } from "../semantic/naming.ts";

const PRIMITIVE_SQL_TYPES = new Set(["Text", "Bool", "Int", "Float"]);

export interface SqlSchemaColumn {
	name: string;
	sqlType: string;
	comment?: string;
	primaryKey?: boolean;
	notNull?: boolean;
	defaultSql?: string;
}

export interface SqlSchemaTable {
	recordName: string;
	tableName: string;
	columns: SqlSchemaColumn[];
}

export function toSqlIdentifier(label: string): string {
	const words = label.match(/[A-Za-z0-9]+/g) ?? [];
	return words.map((word) => word.toLowerCase()).join("_");
}

function recordNames(program: PointSemanticProgram): Set<string> {
	return new Set(
		program.declarations
			.filter((declaration): declaration is PointSemanticRecordDeclaration => declaration.kind === "record")
			.map((declaration) => toPascalCase(declaration.name)),
	);
}

export function mapRecordFieldToSqlColumn(
	fieldLabel: string,
	type: PointSemanticTypeExpression,
	recordNameSet: Set<string>,
): SqlSchemaColumn | undefined {
	const columnName = toSqlIdentifier(fieldLabel);
	if (type.name === "Text") {
		const isId = columnName === "id";
		return {
			name: columnName,
			sqlType: "TEXT",
			primaryKey: isId,
			notNull: isId,
		};
	}
	if (type.name === "Bool") {
		return {
			name: columnName,
			sqlType: "BOOLEAN",
			notNull: true,
			defaultSql: "FALSE",
		};
	}
	if (type.name === "Int") {
		return {
			name: columnName,
			sqlType: "BIGINT",
		};
	}
	if (type.name === "Float") {
		return {
			name: columnName,
			sqlType: "DOUBLE PRECISION",
		};
	}
	if (type.name === "List") {
		const inner = type.args[0];
		const innerLabel = inner ? formatTypeExpression(inner) : "unknown";
		return {
			name: columnName,
			sqlType: "TEXT",
			comment: `Point List<${innerLabel}> — store JSON text in this spike`,
		};
	}
	if (recordNameSet.has(type.name)) {
		return {
			name: columnName,
			sqlType: "TEXT",
			comment: `Point nested record ${type.name} — store JSON text in this spike`,
		};
	}
	return undefined;
}

function formatTypeExpression(type: PointSemanticTypeExpression): string {
	if (type.args.length === 0) return type.name;
	return `${type.name}<${type.args.map((arg) => formatTypeExpression(arg)).join(", ")}>`;
}

export function buildSqlSchemaTables(program: PointSemanticProgram): SqlSchemaTable[] {
	const records = program.declarations.filter(
		(declaration): declaration is PointSemanticRecordDeclaration => declaration.kind === "record",
	);
	const recordNameSet = recordNames(program);
	return records.map((record) => ({
		recordName: record.name,
		tableName: toSqlIdentifier(record.name),
		columns: record.fields.flatMap((field) => {
			const column = mapRecordFieldToSqlColumn(field.label, field.type, recordNameSet);
			return column ? [column] : [];
		}),
	}));
}

function formatColumnDefinition(column: SqlSchemaColumn): string {
	const parts = [`${column.name} ${column.sqlType}`];
	if (column.primaryKey) parts.push("PRIMARY KEY");
	if (column.notNull) parts.push("NOT NULL");
	if (column.defaultSql) parts.push(`DEFAULT ${column.defaultSql}`);
	return parts.join(" ");
}

export function emitPointSqlSchema(program: PointSemanticProgram): string {
	const lines: string[] = [
		"-- Generated by Point build-schema. Do not edit directly.",
		...(program.module ? [`-- Point module: ${program.module}`] : []),
		"-- Spike: record-backed DDL stub. Apply with your migration tool; Point does not run migrations.",
		"",
	];
	const tables = buildSqlSchemaTables(program);
	if (tables.length === 0) {
		lines.push("-- No record blocks found in this module.");
		return `${lines.join("\n")}\n`;
	}
	for (const table of tables) {
		lines.push(`-- record ${table.recordName}`);
		if (table.columns.length === 0) {
			lines.push(`-- Skipped ${table.tableName}: no mappable scalar columns`);
			lines.push("");
			continue;
		}
		for (const column of table.columns) {
			if (column.comment) lines.push(`-- ${column.name}: ${column.comment}`);
		}
		lines.push(`CREATE TABLE IF NOT EXISTS ${table.tableName} (`);
		lines.push(
			table.columns
				.map((column, index) => `  ${formatColumnDefinition(column)}${index < table.columns.length - 1 ? "," : ""}`)
				.join("\n"),
		);
		lines.push(");", "");
	}
	return `${lines.join("\n")}\n`;
}
