import type {
	PointCoreDeclaration,
	PointCoreExpression,
	PointCoreFunctionDeclaration,
	PointCoreParameter,
	PointCoreProgram,
	PointCoreStatement,
	PointCoreTypeDeclaration,
	PointCoreValueDeclaration,
} from "./ast.ts";
import type { PointSemanticRouteDeclaration } from "../semantic/ast.ts";
import { semanticFunctionName } from "../semantic/naming.ts";

const BINARY_OPERATORS: Record<string, string> = {
	and: "&&",
	or: "||",
};

/** Emit JavaScript from a core AST program (no type syntax). Production path: parsePointSource → check → emit. */
export function emitPointCoreJavaScript(program: PointCoreProgram): string {
	const routes = program.semanticSource?.declarations.filter((declaration): declaration is PointSemanticRouteDeclaration => declaration.kind === "route") ?? [];
	const routeServeCommand = program.declarations.find((declaration) => declaration.kind === "function" && isRouteServeCommand(declaration));
	const lines: string[] = [];
	lines.push("// Generated by Point. Do not edit directly.");
	if (program.module) lines.push(`// Point module: ${program.module}`);
	lines.push("");
	for (const declaration of program.declarations) {
		if (declaration.kind === "function" && declaration.semantic?.kind === "command" && routes.length > 0 && isRouteServeCommand(declaration)) {
			lines.push(...emitRouteServeCommand(declaration), "");
			continue;
		}
		lines.push(...emitDeclaration(declaration), "");
	}
	if (routes.length > 0 && routeServeCommand) {
		lines.push(...emitRouteServerRuntime(routes), "");
	}
	return `${trimTrailingBlankLines(lines).join("\n")}\n`;
}

function emitDeclaration(declaration: PointCoreDeclaration): string[] {
	if (declaration.kind === "import") {
		return [`import { ${declaration.names.join(", ")} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "external") {
		const imported = declaration.importName ? `${declaration.importName} as ${declaration.name}` : declaration.name;
		return [`import { ${imported} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "type") return [];
	if (declaration.kind === "value") return [emitValue(declaration, true)];
	return emitFunction(declaration);
}

function emitFunction(declaration: PointCoreFunctionDeclaration): string[] {
	const asyncPrefix = declaration.semantic?.kind === "action" || declaration.semantic?.kind === "workflow" || declaration.semantic?.kind === "command" ? "async " : "";
	const bodyLines =
		declaration.semantic?.kind === "page" && declaration.semantic.pageLayout
			? [`return ${emitExpression(declaration.semantic.pageLayout.main)};`]
			: declaration.body.flatMap((statement) => emitStatement(statement, declaration.semantic?.kind));
	return [
		`export ${asyncPrefix}function ${declaration.name}(${declaration.params.map(emitParam).join(", ")}) {`,
		...indentLines(bodyLines),
		"}",
	];
}

function emitStatement(statement: PointCoreStatement, semanticKind?: string): string[] {
	if (statement.kind === "return") {
		if (semanticKind === "view" && statement.value?.kind === "literal" && typeof statement.value.value === "string") {
			return [`return ${JSON.stringify(statement.value.value)};`];
		}
		return [statement.value ? `return ${emitExpression(statement.value)};` : "return;"];
	}
	if (statement.kind === "value") return [emitValue(statement, false)];
	if (statement.kind === "assignment") return [`${statement.name} ${statement.operator} ${emitExpression(statement.value)};`];
	if (statement.kind === "if") {
		const lines = [
			`if (${emitCondition(statement.condition)}) {`,
			...indentLines(statement.thenBody.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
		if (statement.elseBody.length > 0) {
			lines.push(
				"else {",
				...indentLines(statement.elseBody.flatMap((child) => emitStatement(child, semanticKind))),
				"}",
			);
		}
		return lines;
	}
	if (statement.kind === "for") {
		return [
			`for (const ${statement.itemName} of ${emitExpression(statement.iterable)}) {`,
			...indentLines(statement.body.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
	}
	return [`${emitExpression(statement.value)};`];
}

function emitValue(declaration: PointCoreValueDeclaration, exported: boolean): string {
	const prefix = exported ? "export " : "";
	const keyword = declaration.mutable ? "let" : "const";
	return `${prefix}${keyword} ${declaration.name} = ${emitExpression(declaration.value)};`;
}

function emitParam(param: PointCoreParameter): string {
	return param.name;
}

function emitExpression(expression: PointCoreExpression): string {
	if (expression.kind === "literal") return JSON.stringify(expression.value);
	if (expression.kind === "identifier") return expression.name;
	if (expression.kind === "list") return `[${expression.items.map(emitExpression).join(", ")}]`;
	if (expression.kind === "record") {
		return `{ ${expression.fields.map((field) => `${field.name}: ${emitExpression(field.value)}`).join(", ")} }`;
	}
	if (expression.kind === "await") return `await ${emitExpression(expression.value)}`;
	if (expression.kind === "property") return `${emitExpression(expression.target)}.${expression.name}`;
	if (expression.kind === "call") {
		if (expression.callee === "Error") return `{ message: ${expression.args[0] ? emitExpression(expression.args[0]) : JSON.stringify("")} }`;
		return `${expression.callee}(${expression.args.map(emitExpression).join(", ")})`;
	}
	const operator = BINARY_OPERATORS[expression.operator] ?? expression.operator;
	return `(${emitExpression(expression.left)} ${operator} ${emitExpression(expression.right)})`;
}

function emitCondition(expression: PointCoreExpression): string {
	const emitted = emitExpression(expression);
	return emitted.startsWith("(") && emitted.endsWith(")") ? emitted.slice(1, -1) : emitted;
}

function indentLines(lines: string[]): string[] {
	return lines.map((line) => `  ${line}`);
}

function trimTrailingBlankLines(lines: string[]): string[] {
	while (lines.at(-1) === "") lines.pop();
	return lines;
}

function isRouteServeCommand(declaration: PointCoreFunctionDeclaration): boolean {
	return declaration.semantic?.name === "serve store readiness" || declaration.name === "serveStoreReadinessCommand";
}

function emitRouteServeCommand(declaration: PointCoreFunctionDeclaration): string[] {
	const asyncPrefix = declaration.semantic?.kind === "command" ? "async " : "";
	return [
		`export ${asyncPrefix}function ${declaration.name}(${declaration.params.map(emitParam).join(", ")}) {`,
		"  const port = Number(process.env.PORT ?? 3456);",
		"  const server = Bun.serve({ port, fetch: createPointRouteFetchHandler() });",
		"  console.log(`Store readiness listening on http://localhost:${server.port}`);",
		"  await new Promise(() => {});",
		"}",
	];
}

function emitRouteServerRuntime(routes: PointSemanticRouteDeclaration[]): string[] {
	const matchers = routes.map((route) => {
		const handlerName = semanticFunctionName(route.name, "route", "route");
		const pattern = route.path.replace(/:[A-Za-z][A-Za-z0-9_]*/g, "([^/]+)").replace(/\//g, "\\/");
		const argExpressions = route.inputs.map((_input, index) => `match[${index + 1}]`);
		return {
			method: route.method.toUpperCase(),
			pattern,
			handlerName,
			argExpressions,
		};
	});
	const matchLines = matchers.flatMap((matcher) => [
		`  if (req.method === ${JSON.stringify(matcher.method)} && new RegExp(${JSON.stringify(`^${matcher.pattern}$`)}).test(url.pathname)) {`,
		`    const match = url.pathname.match(new RegExp(${JSON.stringify(`^${matcher.pattern}$`)}));`,
		`    const body = ${matcher.handlerName}(${matcher.argExpressions.join(", ")});`,
		'    return new Response(typeof body === "string" ? body : body, { headers: { "content-type": "application/json" } });',
		"  }",
	]);
	return [
		"export function createPointRouteFetchHandler() {",
		"  return async (req) => {",
		"    const url = new URL(req.url);",
		...matchLines,
		'    return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers: { "content-type": "application/json" } });',
		"  };",
		"}",
		"",
		"export function startRoutesServer() {",
		"  const port = Number(process.env.PORT ?? 3456);",
		"  return Bun.serve({ port, fetch: createPointRouteFetchHandler() });",
		"}",
	];
}
