import type {
	PointCoreDeclaration,
	PointCoreExpression,
	PointCoreFunctionDeclaration,
	PointCoreParameter,
	PointCoreProgram,
	PointCoreStatement,
	PointCoreTypeDeclaration,
	PointCoreValueDeclaration,
} from "./ast.ts";

const BINARY_OPERATORS: Record<string, string> = {
	and: "&&",
	or: "||",
};

/** Emit JavaScript from a core AST program (no type syntax). Production path: parsePointSource → check → emit. */
export function emitPointCoreJavaScript(program: PointCoreProgram): string {
	const lines: string[] = [];
	lines.push("// Generated by Point. Do not edit directly.");
	if (program.module) lines.push(`// Point module: ${program.module}`);
	lines.push("");
	for (const declaration of program.declarations) {
		lines.push(...emitDeclaration(declaration), "");
	}
	return `${trimTrailingBlankLines(lines).join("\n")}\n`;
}

function emitDeclaration(declaration: PointCoreDeclaration): string[] {
	if (declaration.kind === "import") {
		return [`import { ${declaration.names.join(", ")} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "external") {
		const imported = declaration.importName ? `${declaration.importName} as ${declaration.name}` : declaration.name;
		return [`import { ${imported} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "type") return [];
	if (declaration.kind === "value") return [emitValue(declaration, true)];
	return emitFunction(declaration);
}

function emitFunction(declaration: PointCoreFunctionDeclaration): string[] {
	const asyncPrefix = declaration.semantic?.kind === "action" || declaration.semantic?.kind === "workflow" || declaration.semantic?.kind === "command" ? "async " : "";
	return [
		`export ${asyncPrefix}function ${declaration.name}(${declaration.params.map(emitParam).join(", ")}) {`,
		...indentLines(declaration.body.flatMap((statement) => emitStatement(statement, declaration.semantic?.kind))),
		"}",
	];
}

function emitStatement(statement: PointCoreStatement, semanticKind?: string): string[] {
	if (statement.kind === "return") {
		if (semanticKind === "view" && statement.value?.kind === "literal" && typeof statement.value.value === "string") {
			return [`return ${JSON.stringify(statement.value.value)};`];
		}
		return [statement.value ? `return ${emitExpression(statement.value)};` : "return;"];
	}
	if (statement.kind === "value") return [emitValue(statement, false)];
	if (statement.kind === "assignment") return [`${statement.name} ${statement.operator} ${emitExpression(statement.value)};`];
	if (statement.kind === "if") {
		const lines = [
			`if (${emitCondition(statement.condition)}) {`,
			...indentLines(statement.thenBody.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
		if (statement.elseBody.length > 0) {
			lines.push(
				"else {",
				...indentLines(statement.elseBody.flatMap((child) => emitStatement(child, semanticKind))),
				"}",
			);
		}
		return lines;
	}
	if (statement.kind === "for") {
		return [
			`for (const ${statement.itemName} of ${emitExpression(statement.iterable)}) {`,
			...indentLines(statement.body.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
	}
	return [`${emitExpression(statement.value)};`];
}

function emitValue(declaration: PointCoreValueDeclaration, exported: boolean): string {
	const prefix = exported ? "export " : "";
	const keyword = declaration.mutable ? "let" : "const";
	return `${prefix}${keyword} ${declaration.name} = ${emitExpression(declaration.value)};`;
}

function emitParam(param: PointCoreParameter): string {
	return param.name;
}

function emitExpression(expression: PointCoreExpression): string {
	if (expression.kind === "literal") return JSON.stringify(expression.value);
	if (expression.kind === "identifier") return expression.name;
	if (expression.kind === "list") return `[${expression.items.map(emitExpression).join(", ")}]`;
	if (expression.kind === "record") {
		return `{ ${expression.fields.map((field) => `${field.name}: ${emitExpression(field.value)}`).join(", ")} }`;
	}
	if (expression.kind === "await") return `await ${emitExpression(expression.value)}`;
	if (expression.kind === "property") return `${emitExpression(expression.target)}.${expression.name}`;
	if (expression.kind === "call") {
		if (expression.callee === "Error") return `{ message: ${expression.args[0] ? emitExpression(expression.args[0]) : JSON.stringify("")} }`;
		return `${expression.callee}(${expression.args.map(emitExpression).join(", ")})`;
	}
	const operator = BINARY_OPERATORS[expression.operator] ?? expression.operator;
	return `(${emitExpression(expression.left)} ${operator} ${emitExpression(expression.right)})`;
}

function emitCondition(expression: PointCoreExpression): string {
	const emitted = emitExpression(expression);
	return emitted.startsWith("(") && emitted.endsWith(")") ? emitted.slice(1, -1) : emitted;
}

function indentLines(lines: string[]): string[] {
	return lines.map((line) => `  ${line}`);
}

function trimTrailingBlankLines(lines: string[]): string[] {
	while (lines.at(-1) === "") lines.pop();
	return lines;
}
