import type {
	PointCoreDeclaration,
	PointCoreExpression,
	PointCoreFunctionDeclaration,
	PointCoreParameter,
	PointCoreProgram,
	PointCoreStatement,
	PointCoreTypeDeclaration,
	PointCoreValueDeclaration,
	PointSourceSpan,
} from "./ast.ts";
import type { PointSemanticMiddlewareDeclaration, PointSemanticRouteDeclaration, PointSemanticScheduleDeclaration, PointSemanticStreamRouteDeclaration } from "../semantic/ast.ts";
import { emitRouteServerRuntime } from "./emit-routes.ts";
import { emitScheduleRuntime, emitScheduleRunCommand, isScheduleRunCommand } from "./emit-schedules.ts";
import { toIdentifier, toPascalCase } from "../semantic/naming.ts";
import { tagEmittedLine } from "./source-map.ts";

const BINARY_OPERATORS: Record<string, string> = {
	and: "&&",
	or: "||",
};

export interface EmitJavaScriptOptions {
	/** Optimized emit for deploy: production header and compact blank lines (host minifier still recommended). */
	production?: boolean;
}

export const PRODUCTION_EMIT_HEADER =
	"// Point production build — host bundler/minifier recommended; see docs/site/toolchain/deploy.md";

/** Emit JavaScript from a core AST program (no type syntax). Production path: parsePointSource → check → emit. */
export function emitPointCoreJavaScript(program: PointCoreProgram, options: EmitJavaScriptOptions = {}): string {
	const routes = program.semanticSource?.declarations.filter((declaration): declaration is PointSemanticRouteDeclaration => declaration.kind === "route") ?? [];
	const streamRoutes =
		program.semanticSource?.declarations.filter((declaration): declaration is PointSemanticStreamRouteDeclaration => declaration.kind === "streamRoute") ?? [];
	const schedules =
		program.semanticSource?.declarations.filter((declaration): declaration is PointSemanticScheduleDeclaration => declaration.kind === "schedule") ?? [];
	const routeServeCommand = program.declarations.find((declaration) => declaration.kind === "function" && isRouteServeCommand(declaration));
	const scheduleRunCommand = program.declarations.find((declaration) => declaration.kind === "function" && isScheduleRunCommand(declaration));
	const actionFnByName = buildActionFnMap(program);
	const lines: string[] = [];
	lines.push("// Generated by Point. Do not edit directly.");
	if (program.module) lines.push(`// Point module: ${program.module}`);
	lines.push("");
	for (const declaration of program.declarations) {
		if (declaration.kind === "function" && declaration.semantic?.kind === "command" && (routes.length > 0 || streamRoutes.length > 0) && isRouteServeCommand(declaration)) {
			lines.push(...emitRouteServeCommand(declaration), "");
			continue;
		}
		if (declaration.kind === "function" && declaration.semantic?.kind === "command" && schedules.length > 0 && isScheduleRunCommand(declaration)) {
			lines.push(...emitScheduleRunCommand(declaration), "");
			continue;
		}
		lines.push(...emitDeclaration(declaration), "");
	}
	if ((routes.length > 0 || streamRoutes.length > 0) && routeServeCommand) {
		const middlewareByName = buildMiddlewareMap(program.semanticSource?.declarations ?? []);
		const records = buildRecordFieldMap(program.semanticSource?.declarations ?? []);
		lines.push(...emitRouteServerRuntime(routes, streamRoutes, middlewareByName, records, actionFnByName), "");
	}
	if (schedules.length > 0) {
		lines.push(...emitScheduleRuntime(schedules, actionFnByName), "");
	}
	const body = `${trimTrailingBlankLines(lines).join("\n")}\n`;
	return options.production ? formatProductionJavaScript(body) : body;
}

/** Compact spacing and tag production emit for deploy pipelines. */
export function formatProductionJavaScript(source: string): string {
	const lines = source.replace(/\r\n/g, "\n").split("\n");
	const generatedIndex = lines.findIndex((line) => line.startsWith("// Generated by Point"));
	if (generatedIndex >= 0) lines.splice(generatedIndex + 1, 0, PRODUCTION_EMIT_HEADER);
	else lines.unshift(PRODUCTION_EMIT_HEADER);
	const compacted: string[] = [];
	let prevBlank = false;
	for (const line of lines) {
		const trimmed = line.trimEnd();
		const isBlank = trimmed.length === 0;
		if (isBlank && prevBlank) continue;
		compacted.push(trimmed);
		prevBlank = isBlank;
	}
	return `${compacted.join("\n").replace(/\n+$/, "\n")}`;
}

function emitDeclaration(declaration: PointCoreDeclaration): string[] {
	if (declaration.kind === "import") {
		return [`import { ${declaration.names.join(", ")} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "external") {
		const imported = declaration.importName ? `${declaration.importName} as ${declaration.name}` : declaration.name;
		return [`import { ${imported} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "type") return [];
	if (declaration.kind === "value") return [emitValue(declaration, true)];
	return emitFunction(declaration);
}

function emitFunction(declaration: PointCoreFunctionDeclaration): string[] {
	const isStreamAction = declaration.semantic?.isStreamAction === true;
	const asyncPrefix = isStreamAction
		? "async function* "
		: declaration.semantic?.kind === "action" ||
				declaration.semantic?.kind === "workflow" ||
				declaration.semantic?.kind === "pipeline" ||
				declaration.semantic?.kind === "command"
			? "async "
			: "";
	const bodyLines =
		declaration.semantic?.kind === "page" && declaration.semantic.pageLayout
			? [`return ${emitExpression(declaration.semantic.pageLayout.main)};`]
			: declaration.body.flatMap((statement) => emitStatement(statement, declaration.semantic?.kind));
	return [
		`export ${isStreamAction ? "async function* " : asyncPrefix ? "async function " : "function "}${declaration.name}(${declaration.params.map(emitParam).join(", ")}) {`,
		...indentLines(bodyLines),
		"}",
	];
}

function emitStatement(statement: PointCoreStatement, semanticKind?: string): string[] {
	if (statement.kind === "yield") {
		const span = statementSpan(statement);
		return [tagEmittedLine(statement.value ? `yield* ${emitExpression(statement.value)};` : "yield;", span)];
	}
	if (statement.kind === "return") {
		const span = statementSpan(statement);
		if (semanticKind === "view" && statement.value?.kind === "literal" && typeof statement.value.value === "string") {
			return [tagEmittedLine(`return ${JSON.stringify(statement.value.value)};`, span)];
		}
		return [tagEmittedLine(statement.value ? `return ${emitExpression(statement.value)};` : "return;", span)];
	}
	if (statement.kind === "value") return [emitValue(statement, false)];
	if (statement.kind === "assignment") {
		return [tagEmittedLine(`${statement.name} ${statement.operator} ${emitExpression(statement.value)};`, statement.span)];
	}
	if (statement.kind === "if") {
		const lines = [
			tagEmittedLine(`if (${emitCondition(statement.condition)}) {`, statement.span),
			...indentLines(statement.thenBody.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
		if (statement.elseBody.length > 0) {
			lines.push(
				"else {",
				...indentLines(statement.elseBody.flatMap((child) => emitStatement(child, semanticKind))),
				"}",
			);
		}
		return lines;
	}
	if (statement.kind === "for") {
		return [
			tagEmittedLine(`for (const ${statement.itemName} of ${emitExpression(statement.iterable)}) {`, statement.span),
			...indentLines(statement.body.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
	}
	return [tagEmittedLine(`${emitExpression(statement.value)};`, statementSpan(statement))];
}

function emitValue(declaration: PointCoreValueDeclaration, exported: boolean): string {
	const prefix = exported ? "export " : "";
	const keyword = declaration.mutable ? "let" : "const";
	return tagEmittedLine(`${prefix}${keyword} ${declaration.name} = ${emitExpression(declaration.value)};`, declaration.span);
}

function statementSpan(statement: PointCoreStatement): PointSourceSpan | undefined {
	if (statement.kind === "return") return statement.span ?? statement.value?.span;
	if (statement.kind === "expression") return statement.span ?? statement.value.span;
	return statement.span;
}

function emitParam(param: PointCoreParameter): string {
	return param.name;
}

function emitExpression(expression: PointCoreExpression): string {
	if (expression.kind === "literal") return JSON.stringify(expression.value);
	if (expression.kind === "identifier") return expression.name;
	if (expression.kind === "list") return `[${expression.items.map(emitExpression).join(", ")}]`;
	if (expression.kind === "record") {
		return `{ ${expression.fields.map((field) => `${field.name}: ${emitExpression(field.value)}`).join(", ")} }`;
	}
	if (expression.kind === "variant") {
		const payload = expression.fields.map((field) => `${field.name}: ${emitExpression(field.value)}`).join(", ");
		return payload.length > 0
			? `{ kind: ${JSON.stringify(expression.caseName)}, ${payload} }`
			: `{ kind: ${JSON.stringify(expression.caseName)} }`;
	}
	if (expression.kind === "await") return `await ${emitExpression(expression.value)}`;
	if (expression.kind === "property") return `${emitExpression(expression.target)}.${expression.name}`;
	if (expression.kind === "call") {
		if (expression.callee === "Error") return `{ message: ${expression.args[0] ? emitExpression(expression.args[0]) : JSON.stringify("")} }`;
		if (expression.callee === "pointMapLookup") {
			const mapExpr = expression.args[0] ? emitExpression(expression.args[0]) : "{}";
			const keyExpr = expression.args[1] ? emitExpression(expression.args[1]) : '""';
			return `(${mapExpr}[String(${keyExpr})])`;
		}
		if (expression.callee === "pointMapLiteral") {
			const pairs: string[] = [];
			for (let index = 0; index < expression.args.length; index += 2) {
				const keyArg = expression.args[index];
				const valueArg = expression.args[index + 1];
				const key = keyArg?.kind === "literal" && typeof keyArg.value === "string" ? JSON.stringify(keyArg.value) : '""';
				pairs.push(`${key}: ${valueArg ? emitExpression(valueArg) : "undefined"}`);
			}
			return `{ ${pairs.join(", ")} }`;
		}
		if (expression.callee === "pointJsonResponse") {
			const body = expression.args[0] ? emitExpression(expression.args[0]) : "{}";
			const status = expression.args[1] ? emitExpression(expression.args[1]) : "200";
			const headers = expression.args[2] ? emitExpression(expression.args[2]) : "{}";
			return `pointJsonResponse(${body}, ${status}, ${headers})`;
		}
		return `${expression.callee}(${expression.args.map(emitExpression).join(", ")})`;
	}
	const operator = BINARY_OPERATORS[expression.operator] ?? expression.operator;
	return `(${emitExpression(expression.left)} ${operator} ${emitExpression(expression.right)})`;
}

function emitCondition(expression: PointCoreExpression): string {
	const emitted = emitExpression(expression);
	return emitted.startsWith("(") && emitted.endsWith(")") ? emitted.slice(1, -1) : emitted;
}

function indentLines(lines: string[]): string[] {
	return lines.map((line) => `  ${line}`);
}

function trimTrailingBlankLines(lines: string[]): string[] {
	while (lines.at(-1) === "") lines.pop();
	return lines;
}

function isRouteServeCommand(declaration: PointCoreFunctionDeclaration): boolean {
	const name = declaration.semantic?.name ?? "";
	return name.toLowerCase().startsWith("serve ");
}

function buildActionFnMap(program: PointCoreProgram): Map<string, string> {
	const actionFnByName = new Map<string, string>();
	for (const declaration of program.declarations) {
		if (declaration.kind === "function" && declaration.semantic?.kind === "action") {
			actionFnByName.set(declaration.semantic.name, declaration.name);
		}
	}
	return actionFnByName;
}

function buildMiddlewareMap(
	declarations: Array<{ kind: string; name?: string } & Partial<PointSemanticMiddlewareDeclaration>>,
): Map<string, PointSemanticMiddlewareDeclaration> {
	const middlewareByName = new Map<string, PointSemanticMiddlewareDeclaration>();
	for (const declaration of declarations) {
		if (declaration.kind === "middleware" && declaration.name) {
			middlewareByName.set(declaration.name, declaration as PointSemanticMiddlewareDeclaration);
		}
	}
	return middlewareByName;
}

function buildRecordFieldMap(
	declarations: Array<{ kind: string; name?: string; fields?: Array<{ label: string }> }>,
): Map<string, Map<string, string>> {
	const records = new Map<string, Map<string, string>>();
	for (const declaration of declarations) {
		if (declaration.kind !== "record" || !declaration.name || !declaration.fields) continue;
		const fields = new Map<string, string>();
		for (const field of declaration.fields) {
			fields.set(field.label, toIdentifier(field.label));
		}
		records.set(toPascalCase(declaration.name), fields);
	}
	return records;
}

function emitRouteServeCommand(declaration: PointCoreFunctionDeclaration): string[] {
	const asyncPrefix = declaration.semantic?.kind === "command" ? "async " : "";
	return [
		`export ${asyncPrefix}function ${declaration.name}(${declaration.params.map(emitParam).join(", ")}) {`,
		"  const port = Number(process.env.PORT ?? 3456);",
		"  const server = Bun.serve({",
		"    port,",
		"    fetch: createPointRouteFetchHandler(),",
		"    ...(typeof createPointRouteWebSocketHandlers === \"function\" ? { websocket: createPointRouteWebSocketHandlers() } : {}),",
		"  });",
		"  console.log(`Routes listening on http://localhost:${server.port}`);",
		"  await new Promise(() => {});",
		"}",
	];
}
