import type {
	PointCoreDeclaration,
	PointCoreExpression,
	PointCoreFunctionDeclaration,
	PointCoreParameter,
	PointCorePrimitiveType,
	PointCoreProgram,
	PointCoreStatement,
	PointCoreTypeDeclaration,
	PointCoreTypeExpression,
	PointCoreValueDeclaration,
	PointSemanticPageLayout,
	PointSemanticViewCheckboxBinding,
	PointSemanticViewControls,
} from "./ast.ts";

const BINARY_OPERATORS: Record<string, string> = {
	and: "&&",
	or: "||",
};

/** Emit TypeScript from a core AST program. Production path: parsePointSource → check → emit. */
export function emitPointCoreTypeScript(program: PointCoreProgram): string {
	const lines: string[] = [];
	lines.push("// Generated by Point. Do not edit directly.");
	if (program.module) lines.push(`// Point module: ${program.module}`);
	lines.push("");
	for (const declaration of program.declarations) {
		lines.push(...emitDeclaration(declaration), "");
	}
	return `${trimTrailingBlankLines(lines).join("\n")}\n`;
}

function emitDeclaration(declaration: PointCoreDeclaration): string[] {
	if (declaration.kind === "import") {
		return [`import { ${declaration.names.join(", ")} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "external") {
		const imported = declaration.importName ? `${declaration.importName} as ${declaration.name}` : declaration.name;
		return [`import { ${imported} } from ${JSON.stringify(declaration.from)};`];
	}
	if (declaration.kind === "type") return emitType(declaration);
	if (declaration.kind === "value") return [emitValue(declaration, true)];
	return emitFunction(declaration);
}

function emitType(declaration: PointCoreTypeDeclaration): string[] {
	return [
		`export interface ${declaration.name} {`,
		...declaration.fields.map((field) => `  ${field.name}: ${emitTypeExpression(field.type)};`),
		"}",
	];
}

function emitFunction(declaration: PointCoreFunctionDeclaration): string[] {
	const asyncPrefix = declaration.semantic?.kind === "action" || declaration.semantic?.kind === "workflow" || declaration.semantic?.kind === "command" ? "async " : "";
	const returnType =
		declaration.semantic?.kind === "action" || declaration.semantic?.kind === "workflow" || declaration.semantic?.kind === "command"
			? `Promise<${emitTypeExpression(declaration.returnType)}>`
			: declaration.semantic?.kind === "view" || declaration.semantic?.kind === "page"
				? "JSX.Element"
				: declaration.semantic?.kind === "route"
					? "Response | string"
				: emitTypeExpression(declaration.returnType);
	const viewControls = declaration.semantic?.viewControls;
	const bodyLines =
		declaration.semantic?.kind === "page" && declaration.semantic.pageLayout
			? emitPageBody(declaration.semantic.pageLayout)
			: declaration.semantic?.kind === "view" && viewControls
				? emitControlledViewBody(declaration.body, viewControls)
				: declaration.body.flatMap((statement) => emitStatement(statement, declaration.semantic?.kind));
	return [
		`export ${asyncPrefix}function ${declaration.name}(${declaration.params.map(emitParam).join(", ")}): ${returnType} {`,
		...indentLines(bodyLines),
		"}",
	];
}

function emitControlledViewBody(body: PointCoreStatement[], controls: PointSemanticViewControls): string[] {
	const checkboxLines = controls.checkboxes.map((binding) => emitCheckboxControl(binding, controls.changeCallback));
	const contentJsx = emitViewContentExpression(body);
	return ["return (", "  <>", ...indentLines(checkboxLines), `    ${contentJsx}`, "  </>", ");"];
}

function emitCheckboxControl(binding: PointSemanticViewCheckboxBinding, changeCallback: string): string {
	const checked = emitExpression(binding.target);
	return `<label><input type="checkbox" checked={${checked}} onChange={(e) => ${changeCallback}({ ...${binding.recordParam}, ${binding.fieldName}: e.target.checked })} />${escapeJsxText(binding.label)}</label>`;
}

function emitViewContentExpression(body: PointCoreStatement[]): string {
	let expression = "null";
	for (let index = body.length - 1; index >= 0; index -= 1) {
		const statement = body[index];
		if (!statement) continue;
		if (statement.kind === "return" && statement.value) {
			expression = emitViewRenderFragment(statement.value);
			continue;
		}
		if (statement.kind === "if" && statement.thenBody.length === 1 && statement.thenBody[0]?.kind === "return" && statement.thenBody[0].value) {
			const thenValue = emitViewRenderFragment(statement.thenBody[0].value);
			expression = `${emitCondition(statement.condition)} ? ${thenValue} : ${expression}`;
		}
	}
	return `{${expression}}`;
}

function emitViewRenderFragment(expression: PointCoreExpression): string {
	if (expression.kind === "literal" && typeof expression.value === "string") {
		return `<>${escapeJsxText(expression.value)}</>`;
	}
	return `<>{${emitExpression(expression)}}</>`;
}

function emitPageBody(layout: PointSemanticPageLayout): string[] {
	const title = emitJsxChild(layout.title);
	const description = layout.description ? `\n      <p className="point-page-description">${emitJsxChild(layout.description)}</p>` : "";
	const main = emitJsxChild(layout.main, true);
	return [
		`return (`,
		`  <main className="point-page">`,
		`    <header className="point-page-header">`,
		`      <h1>${title}</h1>${description}`,
		`    </header>`,
		`    <section className="point-page-main">${main}</section>`,
		`  </main>`,
		`);`,
	];
}

function emitJsxChild(expression: PointCoreExpression, allowComponent = false): string {
	if (expression.kind === "literal" && typeof expression.value === "string") {
		return escapeJsxText(expression.value);
	}
	if (allowComponent) {
		return `{${emitExpression(expression)}}`;
	}
	return `{${emitExpression(expression)}}`;
}

function emitStatement(statement: PointCoreStatement, semanticKind?: string): string[] {
	if (statement.kind === "return") {
		if (semanticKind === "view" && statement.value) {
			if (statement.value.kind === "literal" && typeof statement.value.value === "string") {
				return [`return <>${escapeJsxText(statement.value.value)}</>;`];
			}
			return [`return <>{${emitExpression(statement.value)}}</>;`];
		}
		return [statement.value ? `return ${emitExpression(statement.value)};` : "return;"];
	}
	if (statement.kind === "value") return [emitValue(statement, false)];
	if (statement.kind === "assignment") return [`${statement.name} ${statement.operator} ${emitExpression(statement.value)};`];
	if (statement.kind === "if") {
		const lines = [
			`if (${emitCondition(statement.condition)}) {`,
			...indentLines(statement.thenBody.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
		if (statement.elseBody.length > 0) {
			lines.push(
				"else {",
				...indentLines(statement.elseBody.flatMap((child) => emitStatement(child, semanticKind))),
				"}",
			);
		}
		return lines;
	}
	if (statement.kind === "for") {
		return [
			`for (const ${statement.itemName} of ${emitExpression(statement.iterable)}) {`,
			...indentLines(statement.body.flatMap((child) => emitStatement(child, semanticKind))),
			"}",
		];
	}
	return [`${emitExpression(statement.value)};`];
}

function escapeJsxText(value: string): string {
	return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

function emitValue(declaration: PointCoreValueDeclaration, exported: boolean): string {
	const prefix = exported ? "export " : "";
	const keyword = declaration.mutable ? "let" : "const";
	return `${prefix}${keyword} ${declaration.name}: ${emitTypeExpression(declaration.type)} = ${emitExpression(declaration.value)};`;
}

function emitParam(param: PointCoreParameter): string {
	return `${param.name}: ${emitParamType(param.type)}`;
}

function emitParamType(type: PointCoreTypeExpression): string {
	if (type.name === "Handler" && type.args.length === 1) {
		return `(value: ${emitTypeExpression(type.args[0]!)}) => void`;
	}
	return emitTypeExpression(type);
}

function emitTypeExpression(type: PointCoreTypeExpression): string {
	if (type.name === "Handler" && type.args.length === 1) {
		return `(value: ${emitTypeExpression(type.args[0]!)}) => void`;
	}
	if (type.name === "List") return `Array<${type.args[0] ? emitTypeExpression(type.args[0]) : "unknown"}>`;
	if (type.name === "Maybe") return `${type.args[0] ? emitTypeExpression(type.args[0]) : "unknown"} | null`;
	if (type.name === "Or") return type.args.map(emitTypeExpression).join(" | ");
	if (type.name === "Error") return "{ message: string }";
	if (isPrimitiveType(type.name)) return emitPrimitiveType(type.name);
	return type.name;
}

function emitPrimitiveType(type: PointCorePrimitiveType): string {
	if (type === "Text") return "string";
	if (type === "Int" || type === "Float") return "number";
	if (type === "Bool") return "boolean";
	return "void";
}

function emitExpression(expression: PointCoreExpression): string {
	if (expression.kind === "literal") return JSON.stringify(expression.value);
	if (expression.kind === "identifier") return expression.name;
	if (expression.kind === "list") return `[${expression.items.map(emitExpression).join(", ")}]`;
	if (expression.kind === "record") {
		return `{ ${expression.fields.map((field) => `${field.name}: ${emitExpression(field.value)}`).join(", ")} }`;
	}
	if (expression.kind === "await") return `await ${emitExpression(expression.value)}`;
	if (expression.kind === "property") return `${emitExpression(expression.target)}.${expression.name}`;
	if (expression.kind === "call") {
		if (expression.callee === "Error") return `{ message: ${expression.args[0] ? emitExpression(expression.args[0]) : JSON.stringify("")} }`;
		return `${expression.callee}(${expression.args.map(emitExpression).join(", ")})`;
	}
	const operator = BINARY_OPERATORS[expression.operator] ?? expression.operator;
	return `(${emitExpression(expression.left)} ${operator} ${emitExpression(expression.right)})`;
}

function emitCondition(expression: PointCoreExpression): string {
	const emitted = emitExpression(expression);
	return emitted.startsWith("(") && emitted.endsWith(")") ? emitted.slice(1, -1) : emitted;
}

function isPrimitiveType(type: string): type is PointCorePrimitiveType {
	return type === "Text" || type === "Int" || type === "Float" || type === "Bool" || type === "Void";
}

function indentLines(lines: string[]): string[] {
	return lines.map((line) => `  ${line}`);
}

function trimTrailingBlankLines(lines: string[]): string[] {
	while (lines.at(-1) === "") lines.pop();
	return lines;
}
