import type {
	PointCoreDeclaration,
	PointCoreExpression,
	PointCoreExternalDeclaration,
	PointCoreFunctionDeclaration,
	PointCoreParameter,
	PointCorePrimitiveType,
	PointCoreProgram,
	PointCoreStatement,
	PointCoreTypeDeclaration,
	PointCoreTypeExpression,
	PointCoreValueDeclaration,
} from "./ast.ts";

const BINARY_OPERATORS: Record<string, string> = {
	and: "and",
	or: "or",
};

const UNSUPPORTED_SEMANTIC_KINDS = new Set(["view", "page", "route", "workflow", "command"]);

/** True when every declaration is emit-able as Python (no views, routes, workflows, or commands). */
export function isPureLogicProgram(program: PointCoreProgram): boolean {
	return !program.declarations.some((declaration) => declaration.semantic && UNSUPPORTED_SEMANTIC_KINDS.has(declaration.semantic.kind));
}

/** Emit Python from a core AST program (pure logic modules). Production path: parsePointSource → check → emit. */
export function emitPointCorePython(program: PointCoreProgram): string {
	const lines: string[] = [];
	lines.push("# Generated by Point. Do not edit directly.");
	if (program.module) lines.push(`# Point module: ${program.module}`);
	lines.push("");
	lines.push("from __future__ import annotations");
	lines.push("");
	if (program.declarations.some((declaration) => declaration.kind === "type")) {
		lines.push("from typing import TypedDict");
		lines.push("");
	}
	for (const declaration of program.declarations) {
		const emitted = emitDeclaration(declaration);
		if (emitted.length > 0) lines.push(...emitted, "");
	}
	return `${trimTrailingBlankLines(lines).join("\n")}\n`;
}

function emitDeclaration(declaration: PointCoreDeclaration): string[] {
	if (declaration.kind === "import") {
		const moduleName = declaration.from.replace(/^\.\//, "").replace(/-/g, "_");
		return [`from ${toPythonModuleName(moduleName)} import ${declaration.names.join(", ")}`];
	}
	if (declaration.kind === "external") return emitExternal(declaration);
	if (declaration.kind === "type") return emitType(declaration);
	if (declaration.kind === "value") return [emitValue(declaration)];
	if (declaration.semantic && UNSUPPORTED_SEMANTIC_KINDS.has(declaration.semantic.kind)) {
		return [`# Point: ${declaration.semantic.kind} blocks are not supported in Python emit yet`];
	}
	return emitFunction(declaration);
}

function emitType(declaration: PointCoreTypeDeclaration): string[] {
	return [
		`class ${declaration.name}(TypedDict):`,
		...declaration.fields.map((field) => `    ${field.name}: ${emitTypeExpression(field.type)}`),
	];
}

function emitExternal(declaration: PointCoreExternalDeclaration): string[] {
	if (declaration.from === "node:fs" && declaration.importName === "readFileSync") {
		return [
			`def ${declaration.name}(${declaration.params.map(emitParam).join(", ")}) -> ${emitTypeExpression(declaration.returnType)}:`,
			"    from pathlib import Path",
			"    return Path(path).read_text()",
		];
	}
	const moduleName = declaration.from.replace(/^\.\//, "").replace(/-/g, "_");
	const imported = declaration.importName ?? declaration.name;
	return [`from ${toPythonModuleName(moduleName)} import ${imported} as ${declaration.name}`];
}

function emitFunction(declaration: PointCoreFunctionDeclaration): string[] {
	const asyncPrefix = declaration.semantic?.kind === "action" || declaration.semantic?.kind === "workflow" || declaration.semantic?.kind === "command" ? "async " : "";
	return [
		`${asyncPrefix}def ${declaration.name}(${declaration.params.map(emitParam).join(", ")}) -> ${emitReturnType(declaration)}:`,
		...indentLines(declaration.body.flatMap((statement) => emitStatement(statement, declaration.semantic?.kind))),
	];
}

function emitReturnType(declaration: PointCoreFunctionDeclaration): string {
	if (declaration.semantic?.kind === "action" || declaration.semantic?.kind === "workflow" || declaration.semantic?.kind === "command") {
		return emitTypeExpression(declaration.returnType);
	}
	return emitTypeExpression(declaration.returnType);
}

function emitStatement(statement: PointCoreStatement, semanticKind?: string): string[] {
	if (statement.kind === "return") {
		if (semanticKind === "view" || semanticKind === "page") return ["# Point: view/page return values are not supported in Python emit yet", "return \"\""];
		return [statement.value ? `return ${emitExpression(statement.value)}` : "return"];
	}
	if (statement.kind === "value") return [emitValue(statement)];
	if (statement.kind === "assignment") return [`${statement.name} ${statement.operator} ${emitExpression(statement.value)}`];
	if (statement.kind === "if") {
		const lines = [`if ${emitCondition(statement.condition)}:`, ...indentLines(statement.thenBody.flatMap((child) => emitStatement(child, semanticKind)))];
		if (statement.elseBody.length > 0) {
			lines.push("else:", ...indentLines(statement.elseBody.flatMap((child) => emitStatement(child, semanticKind))));
		}
		return lines;
	}
	if (statement.kind === "for") {
		return [`for ${statement.itemName} in ${emitExpression(statement.iterable)}:`, ...indentLines(statement.body.flatMap((child) => emitStatement(child, semanticKind)))];
	}
	return [emitExpression(statement.value)];
}

function emitValue(declaration: PointCoreValueDeclaration): string {
	return `${declaration.name}: ${emitTypeExpression(declaration.type)} = ${emitExpression(declaration.value)}`;
}

function emitParam(param: PointCoreParameter): string {
	return `${param.name}: ${emitTypeExpression(param.type)}`;
}

function emitTypeExpression(type: PointCoreTypeExpression): string {
	if (type.name === "List") return `list[${type.args[0] ? emitTypeExpression(type.args[0]) : "object"}]`;
	if (type.name === "Maybe") return `${type.args[0] ? emitTypeExpression(type.args[0]) : "object"} | None`;
	if (type.name === "Or") return type.args.map(emitTypeExpression).join(" | ");
	if (type.name === "Error") return "dict[str, str]";
	if (isPrimitiveType(type.name)) return emitPrimitiveType(type.name);
	return type.name;
}

function emitPrimitiveType(type: PointCorePrimitiveType): string {
	if (type === "Text") return "str";
	if (type === "Int") return "int";
	if (type === "Float") return "float";
	if (type === "Bool") return "bool";
	return "None";
}

function emitExpression(expression: PointCoreExpression): string {
	if (expression.kind === "literal") return emitLiteral(expression.value);
	if (expression.kind === "identifier") return expression.name;
	if (expression.kind === "list") return `[${expression.items.map(emitExpression).join(", ")}]`;
	if (expression.kind === "record") {
		return `{${expression.fields.map((field) => `"${field.name}": ${emitExpression(field.value)}`).join(", ")}}`;
	}
	if (expression.kind === "await") return `await ${emitExpression(expression.value)}`;
	if (expression.kind === "property") return `${emitExpression(expression.target)}[${JSON.stringify(expression.name)}]`;
	if (expression.kind === "call") {
		if (expression.callee === "Error") {
			const message = expression.args[0] ? emitExpression(expression.args[0]) : '""';
			return `{"message": ${message}}`;
		}
		return `${expression.callee}(${expression.args.map(emitExpression).join(", ")})`;
	}
	const operator = BINARY_OPERATORS[expression.operator] ?? expression.operator;
	return `(${emitExpression(expression.left)} ${operator} ${emitExpression(expression.right)})`;
}

function emitLiteral(value: unknown): string {
	if (value === null) return "None";
	if (value === true) return "True";
	if (value === false) return "False";
	if (typeof value === "string") return JSON.stringify(value);
	return String(value);
}

function emitCondition(expression: PointCoreExpression): string {
	const emitted = emitExpression(expression);
	return emitted.startsWith("(") && emitted.endsWith(")") ? emitted.slice(1, -1) : emitted;
}

function toPythonModuleName(from: string): string {
	return from.replace(/\.ts$/, "").replace(/\.js$/, "").replace(/\.py$/, "");
}

function isPrimitiveType(type: string): type is PointCorePrimitiveType {
	return type === "Text" || type === "Int" || type === "Float" || type === "Bool" || type === "Void";
}

function indentLines(lines: string[]): string[] {
	return lines.map((line) => `    ${line}`);
}

function trimTrailingBlankLines(lines: string[]): string[] {
	while (lines.at(-1) === "") lines.pop();
	return lines;
}
