-- Point LSP for this project (generated by point init)
-- In init.lua: dofile(vim.fn.getcwd() .. "/.point/editors/neovim.lua")

vim.filetype.add({
	extension = {
		point = "point",
	},
})

if not vim.lsp.config then
	vim.notify("Point: Neovim 0.11+ with vim.lsp.config is required", vim.log.levels.WARN)
	return
end

local root = vim.fn.getcwd()
local launcher = root .. "/.point/lsp.mjs"

vim.lsp.config("point", {
	cmd = { "bun", launcher, "lsp" },
	filetypes = { "point" },
	root_markers = { "point.json", "package.json", ".git" },
	settings = {},
})

vim.lsp.enable("point")
